import os
import time

print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
import time
time.sleep(5)

print("Installing wine stageing-deb i386 32bit at stageing /user/home/.wine/config")

import os
os.system("sudo dpkg --add-architecture i386")
import time
time.sleep(0.1)
print("")
print("")
print("")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
import time
time.sleep(0.1)
print("")
print("")
print("")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
import time
time.sleep(0.6)
os.system("sudo wget -nc -O /usr/share/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key")
import time
time.sleep(0.1)
print("")
print("")
print("")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
import time
time.sleep(0.6)
os.system("sudo wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/buster/winehq-buster.sources")
import time
time.sleep(0.1)
print("")
print("")
print("")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
os.system("sudo apt update")
import time
time.sleep(0.1)
print("")
print("")
print("")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
os.system("sudo apt install --install-recommends winehq-staging")
os.system("sudo apt install curl")
os.system("curl https://gitlab.com/brinkervii/grapejuice/-/raw/master/ci_scripts/signing_keys/public_key.gpg | sudo tee /usr/share/keyrings/grapejuice-archive-keyring.gpg")
os.system("sudo tee /etc/apt/sources.list.d/grapejuice.list <<< 'deb [signed-by=/usr/share/keyrings/grapejuice-archive-keyring.gpg] https://brinkervii.gitlab.io/grapejuice/repositories/debian/ universal main'")
os.system("sudo apt update && sudo apt upgrade -y")
os.system("sudo apt install -y grapejuice")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("             !!!Done installing pls restart your chromebook")
print("")
print("Made by Ien Owner of FYC | https://httpanimations.github.io/FYCLIVE/index.html")
